### PR TITLE
deneme5.txt added

### PR DESCRIPTION
**Pull request by ArdaisitanDeneme**
Deneme5.txt added and no conflict.

### CODE REVIEW

**Comment by ArdaIstn** [comment]
Check one more time.

**Comment by ArdaisitanDeneme** [comment]
I checked everything is true  👯

**Comment by ArdaIstn** [comment]
Ok I will check again.

**Comment by ArdaIstn** [comment]
Can you check again

**Comment by ArdaisitanDeneme** [comment]
its ok now.

**Comment by ArdaIstn** [comment]
I merged I hope there will be no conflict.

**Comment by ArdaisitanDeneme** [comment]
:)

**Pull request merged**
